export interface PincodeRecord {
  code: string;
  areaName: string;
  district: string;
  state: string;
}

export const BANGALORE_PINCODES: PincodeRecord[] = [
  { code: "560001", areaName: "Bangalore GPO / MG Road", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560002", areaName: "City Market / Chickpet", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560003", areaName: "Malleshwaram", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560004", areaName: "Basavanagudi", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560005", areaName: "Fraser Town / Pulakeshinagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560008", areaName: "Ulsoor / Halasuru", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560010", areaName: "Rajajinagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560011", areaName: "Jayanagar 3rd Block", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560012", areaName: "Indian Institute of Science (IISc) / Yeshwanthpur", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560016", areaName: "Ramamurthy Nagar / Dooravani Nagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560017", areaName: "Vimanapura / HAL Old Airport Road", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560018", areaName: "Chamrajpet", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560019", areaName: "Gavipuram Extension / Hanumanthanagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560020", areaName: "Seshadripuram", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560021", areaName: "Sriramapuram", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560022", areaName: "Yeshwanthpur Industrial Area", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560023", areaName: "Magadi Road", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560024", areaName: "Hebbal", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560025", areaName: "Richmond Town", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560026", areaName: "Mysore Road / Nayandahalli", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560027", areaName: "Wilson Garden", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560029", areaName: "Dharmaram College / Dairy Circle", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560030", areaName: "Adugodi", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560032", areaName: "RT Nagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560034", areaName: "Koramangala", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560035", areaName: "Carmaram / Sarjapur Road", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560036", areaName: "Krishnarajapuram (KR Puram)", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560037", areaName: "Marathahalli", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560038", areaName: "Indiranagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560039", areaName: "Domlur", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560040", areaName: "Vijayanagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560041", areaName: "Jayanagar 4th Block", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560042", areaName: "Domlur Layout", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560043", areaName: "Banaswadi", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560045", areaName: "Nagavara / Venkateshapura", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560046", areaName: "JC Nagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560047", areaName: "Austin Town", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560048", areaName: "Mahadevapura", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560050", areaName: "Ashok Nagar / Banashankari 1st Stage", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560053", areaName: "Cottonpet", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560054", areaName: "Mathikere", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560056", areaName: "Bangalore University / Jnana Bharathi", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560061", areaName: "Subramanyapura / Uttarahalli", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560064", areaName: "Yelahanka New Town", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560066", areaName: "Whitefield", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560067", areaName: "Kadugodi", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560068", areaName: "Madiwala / BTM Layout", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560070", areaName: "Banashankari 2nd Stage", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560071", areaName: "HAL II Stage", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560072", areaName: "Nagarbhavi", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560073", areaName: "Peenya Industrial Estate", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560075", areaName: "Kaggadasapura", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560076", areaName: "BTM Layout 2nd Stage", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560077", areaName: "Kothanur / Hennur", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560078", areaName: "J P Nagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560079", areaName: "Kamakshipalya", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560083", areaName: "Bannerghatta", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560084", areaName: "St. Thomas Town / Lingarajapuram", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560085", areaName: "Banashankari 3rd Stage", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560086", areaName: "Mahalaxmi Layout", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560087", areaName: "Varthur", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560091", areaName: "Viswaneedam / Herohalli", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560092", areaName: "Sahakarnagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560093", areaName: "Thippasandra", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560094", areaName: "RMV 2nd Stage / Sanjaynagar", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560095", areaName: "Wilson Garden / Koramangala 8th Block", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560096", areaName: "Rajajinagar 6th Block", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560097", areaName: "Vidyaranyapura", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560098", areaName: "Rajarajeshwari Nagar (RR Nagar)", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560099", areaName: "Bommasandra Industrial Area", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560100", areaName: "Electronic City Phase 1", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560102", areaName: "HSR Layout", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560103", areaName: "Devarabeesanahalli / Bellandur", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560104", areaName: "Bannerghatta Road / Arekere", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560105", areaName: "Electronics City Phase 2", district: "Bengaluru Urban", state: "Karnataka" },
  { code: "560107", areaName: "Nelamangala", district: "Bengaluru Rural", state: "Karnataka" },
  { code: "560300", areaName: "Devanahalli / Kempegowda International Airport", district: "Bengaluru Rural", state: "Karnataka" }
];
